### ISSUE TITLE
Script : Moving Player

### ISSUE THREAD

**Issue by martinkunzi** [DoubleSentinel/Peace-Oku#6]

**Comment by DoubleSentinel** [comment]
Move the player with WASD

**Comment by martinkunzi** [comment]
The movements are induced by force vectors and are linked to virtual buttons which are configurable. 

The virtual have the same name but a different number, which is associated to a player ID. 

Roflolilolmao has changed the player control script a lot when he added the pick up option for the player, I believe more informations about controlling the player might be found at #10 

A possible amelioration would be to have an interact button that is different than picking up, in case some objects might be both carriables and interactibles.
